# netlify.toml (Disederhanakan)

# Konfigurasi Build
[build]
  publish = "public"
  functions = "netlify/functions"

# Aturan Redirect untuk API Chat
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
```json
// package.json (Disederhanakan)
{
  "name": "konselor-netlify-project",
  "version": "1.2.1",
  "description": "Aplikasi RASA dengan backend Netlify Functions",
  "dependencies": {
    "node-fetch": "^2.6.9",
    "dotenv": "^16.3.1"
  }
}
