# Konfigurasi Build & Deploy untuk Netlify

[build]
  # Direktori yang berisi semua file frontend Anda (HTML, CSS, JS, dll.)
  publish = "public"
  # Direktori tempat Netlify akan mencari fungsi backend Anda
  functions = "netlify/functions"

# Aturan pengalihan untuk API
# Ini memberitahu Netlify agar setiap permintaan ke /api/... diarahkan ke fungsi yang sesuai.

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

# [[redirects]]
#   from = "/api/synthesize"
#   to = "/.netlify/functions/synthesize"
#   status = 200
